export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD"
export const FETCH_TEMPLATE_DETAILS = "FETCH_TEMPLATE_DETAILS"
export const FETCH_TEMPLATE_REQUEST = "FETCH_TEMPLATE_REQUEST"
export const FETCH_TEMPLATE_SUCCESS = "FETCH_TEMPLATE_SUCCESS"
export const FETCH_TEMPLATE_ERROR = "FETCH_TEMPLATE_ERROR"
export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'
export const CHANGE_ORDER_FIELD = "CHANGE_ORDER_FIELD"
export const CHANGE_DATE_FIELD = 'CHANGE_DATE_FIELD'
export const CHANGE_SELECT_VALUE = 'CHANGE_SELECT_VALUE'

